#!/usr/bin/python3
# SPDX-FileCopyrightText: 2025 Soshi Ohseto <付けたければメールアドレス>
# SPDX-License-Identifier: BSD-3-Clause

import sys

def main() -> None:

    lines = [line.rstrip("\n") for line in sys.stdin]

    if not lines:
        return

    inner_width = max(len(l) for l in lines)

    sample_line = f"*** {'X' * inner_width} ***"
    border = "*" * len(sample_line)

    print(border)
    for l in lines:
        print(f"*** {l:<{inner_width}} ***")
    print(border)


if __name__ == "__main__":
    main()
